title: ISSM Documentation
description: How to install and use the Ice-sheet and Sea-level System Model (ISSM)
url: https://TidbitSoftware.github.io/test_just_the_docs

theme: just-the-docs

aux_links:
  "Make/Suggest Edits": https://github.com/TidbitSoftware/test_just_the_docs
